name: vin_information
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1  # Add this line
  cupertino_icons: ^1.0.6
  fl_chart: ^0.69.0  # Use the latest version
  html: ^0.15.0
  logging: ^1.2.0
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0
  barcode_scan2: ^4.3.3
  url_launcher: ^6.2.4  # Add this line
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0 # Replace with the latest version or desired version
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.0+2

flutter_icons:
  android: true
  ios: false  # Set to false since this is Android only
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  remove_alpha_ios: false  # Not needed for Android
  min_sdk_android: 21  # Android specific

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true