name: vin_information
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1  # Add this line
  cupertino_icons: ^1.0.6
  html: ^0.15.0
  logging: ^1.2.0
  barcode_scan2: ^4.3.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0 # Replace with the latest version or desired version
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true